import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';


const resources = {
  en: { translation: { welcome: 'Welcome to ChatApp', login: 'Login', signup: 'Sign Up', logout: 'Logout', chatRoom: 'Chat Room', settings: 'Settings', profile: 'Profile', send: 'Send', typeMessage: 'Type a message...', online: 'Online', selectLanguage: 'Select Language', fullName: 'Full Name', email: 'Email', password: 'Password', confirmPassword: 'Confirm Password', gender: 'Gender', language: 'Language', male: 'Male', female: 'Female', accountInfo: 'Account Information', editProfile: 'Edit Profile', theme: 'Theme', chooseTheme: 'Choose your preferred theme color for your conversations.', preview: 'Preview', alreadyHaveAccount: 'Already have an account?', enterName: 'Enter your name', enterEmail: 'Enter your email', enterPassword: 'Enter your password', confirmYourPassword: 'Confirm your password', selectGender: 'Select your gender', isRequired: 'is required', minLength: 'must be at least 6 characters', passwordsDoNotMatch: 'Passwords do not match', enterEmail: 'Enter a valid email' } },
  ko: { translation: { welcome: 'ChatApp에 오신 것을 환영합니다', login: '로그인', signup: '회원가입', logout: '로그아웃', chatRoom: '채팅방', settings: '설정', profile: '프로필', send: '보내기', typeMessage: '메시지를 입력하세요...', online: '온라인', selectLanguage: '언어 선택', fullName: '이름', email: '이메일', password: '비밀번호', confirmPassword: '비밀번호 확인', gender: '성별', language: '언어', male: '남성', female: '여성', accountInfo: '계정 정보', editProfile: '프로필 수정', theme: '테마', chooseTheme: '대화에 사용할 테마 색상을 선택하세요.', preview: '미리보기', alreadyHaveAccount: '이미 계정이 있으신가요?', enterName: '이름을 입력하세요', enterEmail: '이메일을 입력하세요', enterPassword: '비밀번호를 입력하세요', confirmYourPassword: '비밀번호를 확인하세요', selectGender: '성별을 선택하세요', isRequired: '필수 항목입니다', minLength: '최소 6자 이상이어야 합니다', passwordsDoNotMatch: '비밀번호가 일치하지 않습니다', enterEmail: '유효한 이메일을 입력하세요' } },
  zh: { translation: { welcome: '欢迎来到ChatApp', login: '登录', signup: '注册', logout: '登出', chatRoom: '聊天室', settings: '设置', profile: '个人资料', send: '发送', typeMessage: '输入消息...', online: '在线', selectLanguage: '选择语言', fullName: '姓名', email: '电子邮件', password: '密码', confirmPassword: '确认密码', gender: '性别', language: '语言', male: '男', female: '女', accountInfo: '账户信息', editProfile: '编辑资料', theme: '主题', chooseTheme: '选择你喜欢的主题颜色。', preview: '预览', alreadyHaveAccount: '已有账户？', enterName: '输入你的姓名', enterEmail: '输入你的电子邮件', enterPassword: '输入你的密码', confirmYourPassword: '确认你的密码', selectGender: '选择你的性别', isRequired: '为必填项', minLength: '至少6个字符', passwordsDoNotMatch: '密码不匹配', enterEmail: '输入有效的电子邮件' } },
  de: { translation: { welcome: 'Willkommen bei ChatApp', login: 'Anmelden', signup: 'Registrieren', logout: 'Abmelden', chatRoom: 'Chatraum', settings: 'Einstellungen', profile: 'Profil', send: 'Senden', typeMessage: 'Nachricht eingeben...', online: 'Online', selectLanguage: 'Sprache wählen', fullName: 'Vollständiger Name', email: 'E-Mail', password: 'Passwort', confirmPassword: 'Passwort bestätigen', gender: 'Geschlecht', language: 'Sprache', male: 'Männlich', female: 'Weiblich', accountInfo: 'Kontoinformationen', editProfile: 'Profil bearbeiten', theme: 'Thema', chooseTheme: 'Wählen Sie Ihre bevorzugte Themenfarbe.', preview: 'Vorschau', alreadyHaveAccount: 'Haben Sie bereits ein Konto?', enterName: 'Geben Sie Ihren Namen ein', enterEmail: 'Geben Sie Ihre E-Mail ein', enterPassword: 'Geben Sie Ihr Passwort ein', confirmYourPassword: 'Bestätigen Sie Ihr Passwort', selectGender: 'Wählen Sie Ihr Geschlecht', isRequired: 'ist erforderlich', minLength: 'muss mindestens 6 Zeichen lang sein', passwordsDoNotMatch: 'Passwörter stimmen nicht überein', enterEmail: 'Geben Sie eine gültige E-Mail ein' } },
  fr: { translation: { welcome: 'Bienvenue sur ChatApp', login: 'Connexion', signup: 'Inscription', logout: 'Déconnexion', chatRoom: 'Salle de chat', settings: 'Paramètres', profile: 'Profil', send: 'Envoyer', typeMessage: 'Tapez un message...', online: 'En ligne', selectLanguage: 'Choisir la langue', fullName: 'Nom complet', email: 'E-mail', password: 'Mot de passe', confirmPassword: 'Confirmer le mot de passe', gender: 'Genre', language: 'Langue', male: 'Homme', female: 'Femme', accountInfo: 'Informations du compte', editProfile: 'Modifier le profil', theme: 'Thème', chooseTheme: 'Choisissez votre couleur de thème préférée.', preview: 'Aperçu', alreadyHaveAccount: 'Vous avez déjà un compte ?', enterName: 'Entrez votre nom', enterEmail: 'Entrez votre e-mail', enterPassword: 'Entrez votre mot de passe', confirmYourPassword: 'Confirmez votre mot de passe', selectGender: 'Sélectionnez votre genre', isRequired: 'est requis', minLength: 'doit comporter au moins 6 caractères', passwordsDoNotMatch: 'Les mots de passe ne correspondent pas', enterEmail: 'Entrez un e-mail valide' } },
  es: { translation: { welcome: 'Bienvenido a ChatApp', login: 'Iniciar sesión', signup: 'Registrarse', logout: 'Cerrar sesión', chatRoom: 'Sala de chat', settings: 'Configuración', profile: 'Perfil', send: 'Enviar', typeMessage: 'Escribe un mensaje...', online: 'En línea', selectLanguage: 'Seleccionar idioma', fullName: 'Nombre completo', email: 'Correo electrónico', password: 'Contraseña', confirmPassword: 'Confirmar contraseña', gender: 'Género', language: 'Idioma', male: 'Masculino', female: 'Femenino', accountInfo: 'Información de la cuenta', editProfile: 'Editar perfil', theme: 'Tema', chooseTheme: 'Elige tu color de tema preferido.', preview: 'Vista previa', alreadyHaveAccount: '¿Ya tienes una cuenta?', enterName: 'Introduce tu nombre', enterEmail: 'Introduce tu correo electrónico', enterPassword: 'Introduce tu contraseña', confirmYourPassword: 'Confirma tu contraseña', selectGender: 'Selecciona tu género', isRequired: 'es obligatorio', minLength: 'debe tener al menos 6 caracteres', passwordsDoNotMatch: 'Las contraseñas no coinciden', enterEmail: 'Introduce un correo electrónico válido' } },
  ja: { translation: { welcome: 'ChatAppへようこそ', login: 'ログイン', signup: '新規登録', logout: 'ログアウト', chatRoom: 'チャットルーム', settings: '設定', profile: 'プロフィール', send: '送信', typeMessage: 'メッセージを入力...', online: 'オンライン', selectLanguage: '言語を選択', fullName: '氏名', email: 'メール', password: 'パスワード', confirmPassword: 'パスワード確認', gender: '性別', language: '言語', male: '男性', female: '女性', accountInfo: 'アカウント情報', editProfile: 'プロフィール編集', theme: 'テーマ', chooseTheme: 'お好みのテーマカラーを選択してください。', preview: 'プレビュー', alreadyHaveAccount: 'すでにアカウントをお持ちですか？', enterName: '氏名を入力してください', enterEmail: 'メールを入力してください', enterPassword: 'パスワードを入力してください', confirmYourPassword: 'パスワードを確認してください', selectGender: '性別を選択してください', isRequired: '必須項目です', minLength: '6文字以上で入力してください', passwordsDoNotMatch: 'パスワードが一致しません', enterEmail: '有効なメールアドレスを入力してください' } },
  ru: { translation: { welcome: 'Добро пожаловать в ChatApp', login: 'Войти', signup: 'Регистрация', logout: 'Выйти', chatRoom: 'Чат', settings: 'Настройки', profile: 'Профиль', send: 'Отправить', typeMessage: 'Введите сообщение...', online: 'Онлайн', selectLanguage: 'Выбрать язык', fullName: 'Полное имя', email: 'Электронная почта', password: 'Пароль', confirmPassword: 'Подтвердите пароль', gender: 'Пол', language: 'Язык', male: 'Мужской', female: 'Женский', accountInfo: 'Информация о аккаунте', editProfile: 'Редактировать профиль', theme: 'Тема', chooseTheme: 'Выберите предпочитаемый цвет темы.', preview: 'Предпросмотр', alreadyHaveAccount: 'Уже есть аккаунт?', enterName: 'Введите ваше имя', enterEmail: 'Введите вашу электронную почту', enterPassword: 'Введите ваш пароль', confirmYourPassword: 'Подтвердите ваш пароль', selectGender: 'Выберите ваш пол', isRequired: 'обязательно', minLength: 'минимум 6 символов', passwordsDoNotMatch: 'Пароли не совпадают', enterEmail: 'Введите действительный адрес электронной почты' } },
  it: { translation: { welcome: 'Benvenuto su ChatApp', login: 'Accedi', signup: 'Registrati', logout: 'Disconnetti', chatRoom: 'Stanza di chat', settings: 'Impostazioni', profile: 'Profilo', send: 'Invia', typeMessage: 'Scrivi un messaggio...', online: 'Online', selectLanguage: 'Seleziona lingua', fullName: 'Nome completo', email: 'Email', password: 'Password', confirmPassword: 'Conferma password', gender: 'Genere', language: 'Lingua', male: 'Maschio', female: 'Femmina', accountInfo: 'Informazioni account', editProfile: 'Modifica profilo', theme: 'Tema', chooseTheme: 'Scegli il colore tema preferito.', preview: 'Anteprima', alreadyHaveAccount: 'Hai già un account?', enterName: 'Inserisci il tuo nome', enterEmail: 'Inserisci la tua email', enterPassword: 'Inserisci la tua password', confirmYourPassword: 'Conferma la tua password', selectGender: 'Seleziona il tuo genere', isRequired: 'è richiesto', minLength: 'deve essere di almeno 6 caratteri', passwordsDoNotMatch: 'Le password non corrispondono', enterEmail: 'Inserisci una email valida' } }
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: localStorage.getItem('lang') || 'en',
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;
